---
title: "Recodeflow test"
format: html
---

```{r}
library(readr)
library(here)
library(huiport)
library(dplyr)
```


1.  Create CHMS synthetic data with missing values. Name of synthetic data has to be name of exact database in order for use in recodeflow. Using only age and sex to keep it simple.

```{r}
# Create synthetic data with missing values
n <- 100  # Number of observations
set.seed(123)  # Set seed for reproducibility

# Generate random ages between 18 and 75, with some missing values [996-999]
ages <- sample(c(18:75, 996:999), n, replace = TRUE)

# Generate random sexes (1 for male, 2 for female, with some missing values [6-9])
sexes <- sample(c(1:2, 6:9), n, replace = TRUE)

# Generate random systolic blood pressures between 80 and 215, with some missing values [996-999]
systolic_bps <- sample(c(80:215, 996:999), n, replace = TRUE)

# Generate random diastolic blood pressures between 50 and 150, with some missing values [996-999]
diastolic_bps <- sample(c(50:150, 996:999), n, replace = TRUE)

# Create a data frame named cycle6
cycle6 <- data.frame(CLC_AGE = ages, CLC_SEX = sexes, bpmdpbps = systolic_bps, bpmdpbpd = diastolic_bps)

# Print the first few rows of the cycle6 data
print(head(cycle6))
write_csv(cycle6, here::here("data", "cycle6.csv"))
```

2.  Load variables and variable-details from worksheets folder.

```{r}
my_variables <- read.csv(here("worksheets", "variables.csv"))
my_variable_details <- read.csv(here("worksheets", "variable-details.csv"))
names(cycle6) <- tolower(names(cycle6)) # Putting all headers to lowercase to ensure easy recoding (cycle6 only)
```

3.  Test recodeflow on fake CHMS data. Refer to console outputs to see results. What do you think?

```{r}
# Recoding basic variables

cycle6_ages <- recodeflow::rec_with_table(cycle6, "clc_age", variable_details = my_variable_details, log = TRUE)
cycle6_sexes <- recodeflow::rec_with_table(cycle6, "clc_sex", variable_details = my_variable_details, log = TRUE)

head(cycle6_ages)
head(cycle6_sexes)

# Recoding a transformed variable (cont to cat)
cycle6_categorical_ages <- recodeflow::rec_with_table(cycle6, "agegroup4", variable_details = my_variable_details, log = TRUE)
head(cycle6_categorical_ages)

# Recoding a derived variable
cycle6_adjusted_SBPs <- recodeflow::rec_with_table(cycle6, c("bpmdpbps", "sbp_adj"), variable_details = my_variable_details, log = TRUE)
head(cycle6_adjusted_SBPs)
```

4.  Generate a Table 1 for synthetic data.

```{r}
transformed_cycle6 <- recodeflow::rec_with_table(cycle6, variables = c("clc_age", "clc_sex", "bpmdpbps", "bpmdpbpd"), variable_details = my_variable_details, notes = FALSE) # It can transform multiple variables at once too!

table1_data <- get_descriptive_data(
  transformed_cycle6,
  my_variables,
  my_variable_details,
  # All the variables whose descriptive statistics we want
  c("clc_age", "clc_sex", "bpmdpbps", "bpmdpbpd"),
  # Sets the stratifier
  list("all" = list("clc_sex"))
)

create_unstratified_descriptive_table( 
  table1_data,
  my_variables,
  my_variable_details
)

```
