---
title: "Centering HTNPoRT Models"
author: "Rafidul Islam"
date: 2025-08-24
format: 
  html:
    toc: true
    html-math-method: katex
    css: styles.css
editor: visual
---

## Load packages and functions

```{r}
#| warning: false
#| message: false
#| output: false

.libPaths("P:/10619/Rpackages")
library(dplyr)
library(rms)

source("R/descriptive-functions.R")
source("R/centering-utils.R") 
# functions in "centering-utils.R"
# get_rcs: implement the formula of rcs components
# step_dummy: dummy variables
# step_rcs: rcs
# step_interaction: interaction terms
# step_center: centering
# get_mean: get mean values from the original dataset
# root.search: Root searching, not in use in this .qmd file
```

## Prepare imputed dataset

Do ctrl+F to change from male to female.

```{r, include = FALSE, warning = FALSE, message = FALSE}
# Synthetic dataset for test use outside RDC
# set.seed(123)
# imputed_cycles1to6_data <- data.frame(
#   highbp14090_adj = sample(1:2, 1000, replace = TRUE), # Binary hypertension outcome
#   highbp14090 = sample(1:2, 1000, replace = TRUE), # Binary unadjusted hypertension outcome
#   control14090_adj = sample(1:2, 1000, replace = TRUE), # Binary controlled hypertension outcome
#   control14090 = sample(1:2, 1000, replace = TRUE), # Binary controlled and unadjusted hypertension outcome
#   ccc_51 = sample(1:2, 1000, replace = TRUE), # Binary self-reported diabetes
#   ckd = sample(1:2, 1000, replace = TRUE), # Binary chronic kidney disease
#   edudr04 = sample(1:3, 1000, replace = TRUE), # Categorical education
#   fmh_15 = sample(1:2, 1000, replace = TRUE), # Binary family history
#   gendmhi = sample(1:2, 1000, replace = TRUE), # Categorical self-rated mental health
#   gen_025 = sample(1:2, 1000, replace = TRUE), # Binary self-perceived stress
#   gen_045 = sample(1:2, 1000, replace = TRUE), # Binary sense of belonging
#   low_drink_score1 = sample(1:4, 1000, replace = TRUE), # Categorical alcohol consumption level
#   married = sample(1:3, 1000, replace = TRUE), # Categorical marital status
#   smoke = sample(1:3, 1000, replace = TRUE), # Categorical smoking status
#   working = sample(1:2, 1000, replace = TRUE), # Binary working status
#   clc_sex = sample(1:2, 1000, replace = TRUE), # Binary sex
#   wgt_full = runif(1000, 0, 1), # Numeric weights
#   clc_age = sample(20:79, 1000, replace = TRUE), # Integer age
#   hwmdbmi = runif(1000, 9.47, 56.77), # Numeric body mass index
#   minperweek = runif(1000, 0, 2004), # Numeric physical activity minutes
#   totalfv = runif(1000, 0, 20), # Numeric fruit and vegetable consumption
#   whr = runif(1000, 25, 100), # Numeric waist-to-height ratio
#   slp_11 = runif(1000, 2, 18), # Numeric sleep duration
#   diabx = sample(1:2, 1000, replace = TRUE), # Binary overall diabetes
#   cycle = sample(1:6, 1000, replace = TRUE), # Cycle variable ranging from 1 to 6
#   anymed2 = sample(0:1, 1000, replace = TRUE), # Binary HTN medication (derived)
#   ccc_32 = sample(1:2, 1000, replace = TRUE), # Binary HTN medication (self-reported)
#   cardiov = sample(1:2, 1000, replace = TRUE), # Binary CVD
#   adj_hh_inc = runif(1000, 20000, 150000), # Numeric income
#   agegroup4 = sample(1:4, 1000, replace = TRUE), # Categorical age group
#   alcdwky = sample(0:84, 1000, replace = TRUE), # Integer alcohol consumption per week
#   bmigroup = sample(1:4, 1000, replace = TRUE), # Categorical BMI group
#   gendhdi = sample(0:4, 1000, replace = TRUE), # Categorical self-rated health
#   gfr = runif(1000, 6, 240), # Numeric glomerular filtration rate
#   hwm_13kg = runif(1000, 42.0, 176.5), # Numeric weight in kg
#   hwm_14cx = runif(1000, 61.4, 162.5), # Numeric waist circumference in cm
#   img_03 = sample(1:2, 1000, replace = TRUE), # Binary immigration variable
#   lab_bpb = runif(1000, 0.009, 1.2), # Numeric blood lead measurement
#   lab_hba1 = runif(1000, 0.042, 0.130), # Numeric HbA1c
#   mvpa150wk = sample(1:2, 1000, replace = TRUE), # Binary moderate-vigorous activity
#   nonhdltodd = sample(1:2, 1000, replace = TRUE), # Binary non-HDL cholesterol
#   gooddiet = sample(1:2, 1000, replace = TRUE), # Binary poor diet indicator
#   pgdcgt = sample(1:13, 1000, replace = TRUE), # Categorical ethnicity
#   bsw1 = runif(1000, 0, 1), # Numeric bootstrap weights
#   bsw2 = runif(1000, 0, 1) # Numeric bootstrap weights
# )

# Truncate skewed continuous variables if necessary
imputed_cycles1to6_data <- truncate_skewed(imputed_cycles1to6_data)

# Recode 2s as 0s in binary predictors and factorize all categorical predictors
imputed_cycles1to6_data <- imputed_cycles1to6_data %>%
  dplyr::mutate(
    highbp14090_adj = ifelse(highbp14090_adj == 2, 0, highbp14090_adj),
    highbp14090 = ifelse(highbp14090 == 2, 0, highbp14090),
    control14090_adj = ifelse(control14090_adj == 2, 0, control14090_adj),
    ckd = ifelse(ckd == 2, 0, ckd),
    diabx = ifelse(diabx == 2, 0, diabx),
    fmh_15 = ifelse(fmh_15 == 2, 0, fmh_15),
    gendmhi = ifelse(gendmhi == 2, 0, gendmhi),
    edudr04 = case_when(
      edudr04 == 1 ~ 2,
      edudr04 == 2 ~ 1,
      edudr04 == 3 ~ 0
    ),
    smoke = case_when(
      smoke == 1 ~ 2,
      smoke == 2 ~ 1,
      smoke == 3 ~ 0
    )
  )

cat_variables <- c("ckd", "diabx", "edudr04", "fmh_15", "gendmhi", "gen_025", "gen_045", "low_drink_score1", "married", "smoke", "working")
imputed_cycles1to6_data <- imputed_cycles1to6_data %>%
  dplyr::mutate(across(all_of(cat_variables), as.factor))

# Separate male  data
male_data <- dplyr::filter(imputed_cycles1to6_data, clc_sex == 1)
```

## Center male models

Do ctrl+F to change from male to female.

```{r}
# -------- dummy variables --------
male_data <- step_dummy(male_data, cat_variables)

# -------- rcs --------
# age
k_age <- 4
rcs.fit <- rcs(male_data$clc_age, k_age)
knots_age <- attributes(rcs.fit)$parms # knot locations
# BMI
k_bmi <- 3
rcs.fit <- rcs(male_data$hwmdbmi, k_bmi)
knots_bmi <- attributes(rcs.fit)$parms # knot locations
# exercise
k_exercise <- 3
rcs.fit <- rcs(male_data$minperweek, k_exercise)
knots_exercise <- attributes(rcs.fit)$parms # knot locations
# unpack rcs
vars_rcs <- c("clc_age", "hwmdbmi", "minperweek")
knots_list <- list(knots_age, knots_bmi, knots_exercise)
knots_list <- setNames(knots_list, vars_rcs)
male_data <- step_rcs(male_data, vars_rcs, knots_list)

# -------- interaction terms --------
interaction_list <- list(
  c("clc_age", "gen_045"),
  c("clc_age", "hwmdbmi"),
  c("clc_age", "minperweek"),
  c("clc_age", "smoke"),
  c("clc_age", "slp_11"),
  c("clc_age", "diabx"),
  c("clc_age", "ckd")
)
male_data <- step_interaction(male_data, interaction_list)

# Apply survey weights to original data
male_data <- male_data %>%
  dplyr::mutate(wgt_full = wgt_full / mean(wgt_full))

male_replicate_weights <- male_data %>%
  dplyr::select(dplyr::starts_with("bsw")) %>%
  names()

weighted_male <- male_data %>%
  srvyr::as_survey_rep(
    weights = wgt_full,
    repweights = all_of(male_replicate_weights),
    type = "bootstrap"
  )

# Get weighted mean values from the ORIGINAL dataset
vars_mean <- c("clc_age_rcs_1", "clc_age_rcs_2", "clc_age_rcs_3", "married_2", "married_3", "edudr04_1", "edudr04_2", "working_2", "gendmhi_1", "gen_025_2", "gen_045_2", "fmh_15_1", "hwmdbmi_rcs_1", "hwmdbmi_rcs_2", "low_drink_score1_2", "low_drink_score1_3", "low_drink_score1_4", "minperweek_rcs_1", "minperweek_rcs_2",
"smoke_1", "smoke_2", "slp_11", "totalfv", "diabx_1", "ckd_1", "clc_age_rcs_1_by_gen_045_2", "clc_age_rcs_2_by_gen_045_2", "clc_age_rcs_3_by_gen_045_2", "clc_age_rcs_1_by_hwmdbmi_rcs_1", "clc_age_rcs_2_by_hwmdbmi_rcs_1", "clc_age_rcs_3_by_hwmdbmi_rcs_1", "clc_age_rcs_1_by_hwmdbmi_rcs_2", "clc_age_rcs_2_by_hwmdbmi_rcs_2", "clc_age_rcs_3_by_hwmdbmi_rcs_2", "clc_age_rcs_1_by_minperweek_rcs_1", "clc_age_rcs_2_by_minperweek_rcs_1", "clc_age_rcs_3_by_minperweek_rcs_1",
"clc_age_rcs_1_by_minperweek_rcs_2", "clc_age_rcs_2_by_minperweek_rcs_2", "clc_age_rcs_3_by_minperweek_rcs_2", "clc_age_rcs_1_by_smoke_1", "clc_age_rcs_2_by_smoke_1", "clc_age_rcs_3_by_smoke_1", "clc_age_rcs_1_by_smoke_2", "clc_age_rcs_2_by_smoke_2", "clc_age_rcs_3_by_smoke_2", "clc_age_rcs_1_by_slp_11", "clc_age_rcs_2_by_slp_11", "clc_age_rcs_3_by_slp_11", "clc_age_rcs_1_by_diabx_1", "clc_age_rcs_2_by_diabx_1", "clc_age_rcs_3_by_diabx_1", "clc_age_rcs_1_by_ckd_1", "clc_age_rcs_2_by_ckd_1", "clc_age_rcs_3_by_ckd_1")

means <- get_mean(weighted_male, vars_mean)

# centering vars in the ORIGINAL dataset
vars_center <- names(means)
male_data_c <- step_center(male_data, vars_center, means)

male_data_c <- male_data_c %>%
  dplyr::mutate(highbp14090_adj = ifelse(highbp14090_adj == 2, 0, highbp14090_adj)) %>%
  dplyr::mutate(wgt_full = wgt_full / mean(wgt_full))

male_replicate_weights <- male_data_c %>%
  dplyr::select(dplyr::starts_with("bsw")) %>%
  names()

weighted_male_c <- male_data_c %>%
  srvyr::as_survey_rep(
    weights = wgt_full,
    repweights = all_of(male_replicate_weights),
    type = "bootstrap"
  )

weighted_male$degf <- 68
male_model <- survey::svyglm(highbp14090_adj ~ rcs(clc_age, 4) + married + edudr04 + working + gendmhi + gen_025 + gen_045 + fmh_15 +  rcs(hwmdbmi, 3) + low_drink_score1 + rcs(minperweek, 3) + smoke + slp_11 + totalfv + diabx + ckd + rcs(clc_age, 4)*gen_045 + rcs(clc_age, 4)*rcs(hwmdbmi, 3) + rcs(clc_age, 4)*rcs(minperweek, 3) + rcs(clc_age, 4)*smoke + rcs(clc_age, 4)*slp_11 + rcs(clc_age, 4)*diabx + rcs(clc_age, 4)*ckd, design = weighted_male, family = quasibinomial())

weighted_male$degf <- 68
male_reduced_model <- survey::svyglm(highbp14090_adj ~ rcs(clc_age, 4) + fmh_15 + rcs(hwmdbmi, 3) + diabx + rcs(clc_age, 4)*rcs(hwmdbmi, 3) + rcs(clc_age, 4)*diabx, design = weighted_male, family = quasibinomial())

weighted_male_c$degf <- 68
male_model_c <- survey::svyglm(highbp14090_adj ~ clc_age_rcs_1_C + clc_age_rcs_2_C + clc_age_rcs_3_C + married_2_C + married_3_C + edudr04_1_C + edudr04_2_C + working_2_C + gendmhi_1_C + gen_025_2_C + gen_045_2_C + fmh_15_1_C + hwmdbmi_rcs_1_C + hwmdbmi_rcs_2_C + low_drink_score1_2_C + low_drink_score1_3_C + low_drink_score1_4_C + minperweek_rcs_1_C + minperweek_rcs_2_C + smoke_1_C + smoke_2_C + slp_11_C + totalfv_C + diabx_1_C + ckd_1_C + clc_age_rcs_1_by_gen_045_2_C + clc_age_rcs_2_by_gen_045_2_C + clc_age_rcs_3_by_gen_045_2_C + clc_age_rcs_1_by_hwmdbmi_rcs_1_C + clc_age_rcs_2_by_hwmdbmi_rcs_1_C + clc_age_rcs_3_by_hwmdbmi_rcs_1_C +  clc_age_rcs_1_by_hwmdbmi_rcs_2_C + clc_age_rcs_2_by_hwmdbmi_rcs_2_C + clc_age_rcs_3_by_hwmdbmi_rcs_2_C + clc_age_rcs_1_by_minperweek_rcs_1_C + 
clc_age_rcs_2_by_minperweek_rcs_1_C + clc_age_rcs_3_by_minperweek_rcs_1_C + 
clc_age_rcs_1_by_minperweek_rcs_2_C + clc_age_rcs_2_by_minperweek_rcs_2_C + 
clc_age_rcs_3_by_minperweek_rcs_2_C + clc_age_rcs_1_by_smoke_1_C + 
clc_age_rcs_2_by_smoke_1_C + clc_age_rcs_3_by_smoke_1_C + clc_age_rcs_1_by_smoke_2_C + 
clc_age_rcs_2_by_smoke_2_C + clc_age_rcs_3_by_smoke_2_C + 
clc_age_rcs_1_by_slp_11_C + clc_age_rcs_2_by_slp_11_C + clc_age_rcs_3_by_slp_11_C +
clc_age_rcs_1_by_diabx_1_C + clc_age_rcs_2_by_diabx_1_C + 
clc_age_rcs_3_by_diabx_1_C + clc_age_rcs_1_by_ckd_1_C + clc_age_rcs_2_by_ckd_1_C + clc_age_rcs_3_by_ckd_1_C, design = weighted_male_c, family = quasibinomial())

weighted_male_c$degf <- 68
male_reduced_model_c <- survey::svyglm(highbp14090_adj ~ clc_age_rcs_1_C + clc_age_rcs_2_C + clc_age_rcs_3_C + fmh_15_1_C + hwmdbmi_rcs_1_C + hwmdbmi_rcs_2_C + diabx_1_C + clc_age_rcs_1_by_hwmdbmi_rcs_1_C + clc_age_rcs_2_by_hwmdbmi_rcs_1_C + clc_age_rcs_3_by_hwmdbmi_rcs_1_C +  clc_age_rcs_1_by_hwmdbmi_rcs_2_C + clc_age_rcs_2_by_hwmdbmi_rcs_2_C + clc_age_rcs_3_by_hwmdbmi_rcs_2_C + clc_age_rcs_1_by_diabx_1_C + clc_age_rcs_2_by_diabx_1_C + 
clc_age_rcs_3_by_diabx_1_C, design = weighted_male_c, family = quasibinomial())

cbind(coef(male_model), coef(male_model_c))
predict(male_model, type = "response") - predict(male_model_c, type = "response")

cbind(coef(male_reduced_model), coef(male_reduced_model_c))
predict(male_reduced_model, type = "response") - predict(male_reduced_model_c, type = "response")
```

## Export beta coefficients and their standard errors

Do ctrl+F to change from male to female.

```{r}
male_centered_betas <- extract_beta_coefs(male_model_c)
male_reduced_centered_betas <- extract_beta_coefs(male_reduced_model_c)

write.csv(male_centered_betas, file = "P:/10619/Dropbox/htnport/vignettes/New Modelling Output/Model Presentation Output/Parameters/Male Full Centered Model Betas.csv")
write.csv(male_reduced_centered_betas, file = "P:/10619/Dropbox/htnport/vignettes/New Modelling Output/Model Presentation Output/Parameters/Male Reduced Centered Model Betas.csv")
```